listeners:
- query_port: 25565
  motd: '&1Another Bungee server'
  priorities:
  - lobby
  bind_local_address: true
  tab_list: GLOBAL_PING
  query_enabled: false
  host: 0.0.0.0:25565
  forced_hosts:
    pvp.md-5.net: pvp
  max_players: 40
  tab_size: 60
  ping_passthrough: false
  force_default_server: true
  proxy_protocol: false
remote_ping_cache: -1
network_compression_threshold: 256
permissions:
  default:
  - null
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
  - report.staff
  - report.delete
  - report.goto
  - report.details
  - report.list
  - System.Team
log_pings: true
connection_throttle_limit: 3
server_connect_timeout: 5000
timeout: 30000
stats: bdfe3c6b-8703-492d-9e35-193cc27822fe
player_limit: -1
ip_forward: true
groups:
  ChrischiMc:
  - admin
remote_ping_timeout: 5000
connection_throttle: 4000
log_commands: false
prevent_proxy_connections: false
online_mode: true
forge_support: false
disabled_commands:
- disabledcommandhere
servers:
  lobby:
    motd: '&1Just another BungeeCord - Forced Host'
    address: localhost:25564
    restricted: false
  su:
    motd: '&1Just another BungeeCord - Forced Host'
    address: localhost:25568
    restricted: false
  kock:
    motd: '&1Just another BungeeCord - Forced Host'
    address: localhost:25566
    restricted: false
  gun:
    motd: '&1Just another BungeeCord - Forced Host'
    address: localhost:25567
    restricted: false
